// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSSLnu1xELTDxSDw_5YmwbKhvYEgKKuA8',
    appId: '1:212561554224:web:461e6bac42ea60fc8576f5',
    messagingSenderId: '212561554224',
    projectId: 'chatapp-476f3',
    authDomain: 'chatapp-476f3.firebaseapp.com',
    storageBucket: 'chatapp-476f3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAss7l7_g4LmjCnG7gt4cY3kuXA3uSV1lw',
    appId: '1:212561554224:android:36fd9c6ea09fc4058576f5',
    messagingSenderId: '212561554224',
    projectId: 'chatapp-476f3',
    storageBucket: 'chatapp-476f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4nG3mdxLirq23yKG1WPW3wJyZ1SLmKzg',
    appId: '1:212561554224:ios:bfd9595620aa50228576f5',
    messagingSenderId: '212561554224',
    projectId: 'chatapp-476f3',
    storageBucket: 'chatapp-476f3.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4nG3mdxLirq23yKG1WPW3wJyZ1SLmKzg',
    appId: '1:212561554224:ios:522aa6cf4b4776808576f5',
    messagingSenderId: '212561554224',
    projectId: 'chatapp-476f3',
    storageBucket: 'chatapp-476f3.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
